language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run test -- --coverage
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./build/